version: 2

builds:
  - binary: "evol"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X hop.top/evol/internal/version.ver={{ .Version }}
        -X hop.top/evol/internal/version.commit={{ .Commit }}
        -X hop.top/evol/internal/version.date={{ .Date }}

archives:
  - format: tar.gz
    name_template: >-
      evol_{{ .Version }}_{{ .Os }}_{{ .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
